### PR TITLE
fix: typescript types

### LINKED ISSUE #8: Inaccurate TypeScript types
The types exported from `index.d.ts` do not match what is actually in `index.js`

### PR DESCRIPTION
**Pull request by wSedlacek**
fixes: #8

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -19,10 +19,5 @@ export {
...
-export type YogaWasm = {
-  init(filepath?: string): Promise<YogaWasm>
-} & YogaStatic
-
-const mod: YogaWasm
-
-export default mod
\ No newline at end of file
+export default function(wasm: ArrayBuffer): YogaStatic;
+export function initStreaming(response: Response): Promise<YogaStatic>;
```
Comment (shuding) [inline index.d.ts:23]: Do we have this exported?

Comment (wSedlacek) [reply index.d.ts:23]: It appears to be exported here
https://github.com/shuding/yoga-wasm-web/blob/4fa5f585cd98dea1b2cf399ab19371a2f3ce084a/index.js#L8-L36

**Comment by shuding** [comment]
Thanks!
